---
checks:
  method-complexity:
    config:
      threshold: 30
  method-lines:
    config:
      threshold: 100
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
    channel: eslint-3
  fixme:
    enabled: true
ratings:
  paths:
  - "*.js"
