sudo: false

language: node_js

node_js:
  - "8.4"
  - "8.3"
  - "8.2"
  - "8.1"
  - "8.0"
  - "7.10"
  - "7.9"
  - "7.8"
  - "7.7"
  - "7.6"
  - "7.5"
  - "7.4"
  - "7.3"
  - "7.2"
  - "7.1"
  - "7.0"
  - "6.10"
  - "6.9"
  - "6.8"
  - "6.7"
  - "6.6"
  - "6.5"
  - "6.4"
  - "6.3"
  - "6.2"
  - "6.1"
  - "6.0"
  - "5.11"
  - "5.10"
  - "5.9"
  - "5.8"
  - "5.7"
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
  - "5.2"
  - "5.1"
  - "5.0"
  - "4.4"
  - "4.3"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"

addons:
  code_climate:
    repo_token: b96c8e14d13e6e0eac109776042700ebba5cddd019d9031fc476d8110842920f

after_script:
  - if [[ `node --version` =~ ^v8.4 ]] ; then npm run coverage ; npm install codeclimate-test-reporter ; codeclimate-test-reporter < coverage/lcov.info ; fi
